name: Backend CD/CD
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: create env file
        run: touch ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: fullstackcicd/tutorial-backend:main
